#!/usr/bin/env python3
r"""Build PG-Label.exe (and, if Inno Setup is present, the installer) on Windows.

Run this ON WINDOWS — PyInstaller freezes for the platform it runs on, so no amount of
configuration makes a Linux machine produce a Windows .exe. Everything beyond a stock Python is
installed into a throwaway venv under ``packaging/build/``, so the machine is left as it was.

    packaging\build.bat                    double-click, or:
    py -3 packaging\build.py               same thing
    py -3 packaging\build.py --installer   also compile the Inno Setup installer
    py -3 packaging\build.py --no-training label-only build (no Train button)
    py -3 packaging\build.py --windowed    no console window (output goes to the log file)
    py -3 packaging\build.py --clean       delete previous build artefacts first

Output
    packaging\dist\PG-Label\PG-Label.exe             the app (a folder — ship all of it)
    packaging\dist\PG-Label-Setup-<version>.exe      the installer (with --installer)

To check a build without a Windows machine in the loop, run ``packaging/verify_build.py``: it
audits the same things this script's smoke test does, plus the payload the spec is supposed to
have produced.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

PKG = Path(__file__).resolve().parent
ROOT = PKG.parent
BUILD = PKG / "build"
DIST = PKG / "dist"
VENV = BUILD / "venv"

sys.path.insert(0, str(ROOT))
from pglabel import console, fsutil  # noqa: E402
console.enable()
from pglabel import paths  # noqa: E402  — the single source of truth for name and version

# The build venv holds only what is needed to freeze: the app's one runtime dependency and the
# freezer itself. Nothing here dictates what the .exe can import.
BUILD_REQUIREMENTS = ["pyinstaller>=6.0", "pillow>=10.0"]


def say(msg: str) -> None:
    print(f"[build] {msg}", flush=True)


def run(cmd, **kw) -> int:
    print(f"\n$ {' '.join(str(c) for c in cmd)}", flush=True)
    return subprocess.call([str(c) for c in cmd], **kw)


def venv_python(venv: Path) -> Path:
    return venv / ("Scripts/python.exe" if os.name == "nt" else "bin/python")


def ensure_build_venv(recreate: bool = False) -> Path:
    py = venv_python(VENV)
    if recreate and VENV.exists():
        if not fsutil.remove_tree(VENV):
            sys.exit(f'[build] {VENV} could not be removed — close anything using it')
    if not py.exists():
        say(f"creating the build environment in {VENV}")
        if run([sys.executable, "-m", "venv", str(VENV)]) != 0:
            sys.exit("[build] could not create the build venv — is this a full Python install?")
    if run([py, "-m", "pip", "install", "--upgrade", "pip"]) != 0:
        sys.exit("[build] pip could not update itself (network/proxy?)")
    if run([py, "-m", "pip", "install", "--upgrade", *BUILD_REQUIREMENTS]) != 0:
        sys.exit("[build] could not install PyInstaller/Pillow (network/proxy?)")
    return py


def write_version_info() -> Path:
    """Generate the Windows VERSIONINFO resource from ``paths.APP_VERSION``.

    Generated rather than checked in, so the .exe properties can never disagree with the version
    the app reports about itself.
    """
    v = paths.APP_VERSION
    parts = [int(x) for x in (v.split(".") + ["0", "0", "0", "0"])[:4]]
    out = PKG / "version_info.txt"
    out.write_text(f"""# Auto-generated by packaging/build.py — edit APP_VERSION in pglabel/paths.py instead.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={tuple(parts)}, prodvers={tuple(parts)},
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('040904B0', [
        StringStruct('CompanyName', '{paths.APP_PUBLISHER}'),
        StringStruct('FileDescription', 'PG-Label — collaborative auto-labeling for object detection'),
        StringStruct('FileVersion', '{v}'),
        StringStruct('InternalName', 'PG-Label'),
        StringStruct('OriginalFilename', 'PG-Label.exe'),
        StringStruct('ProductName', '{paths.APP_NAME}'),
        StringStruct('ProductVersion', '{v}')])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
""", encoding="utf-8")
    return out


def ensure_icon(py: Path) -> None:
    if not (PKG / "assets" / "pglabel.ico").exists():
        say("drawing the app icon")
        run([py, str(PKG / "make_icon.py")])


def smoke_test(exe: Path) -> bool:
    """Start the frozen app in its cheapest mode; a broken bundle fails here, not on a user's PC."""
    say("smoke-testing the frozen app (--where)")
    try:
        out = subprocess.run([str(exe), "--where"], capture_output=True, text=True, timeout=180)
    except Exception as e:
        say(f"smoke test could not run: {e}")
        return False
    print(out.stdout.strip() or out.stderr.strip())
    ok = out.returncode == 0 and '"bundle_root"' in out.stdout
    say("smoke test PASSED" if ok else f"smoke test FAILED (exit {out.returncode})")
    return ok


def find_iscc() -> Path | None:
    """Inno Setup's compiler, if it is installed."""
    found = shutil.which("iscc") or shutil.which("ISCC")
    if found:
        return Path(found)
    for base in (os.environ.get("PROGRAMFILES(X86)", r"C:\Program Files (x86)"),
                 os.environ.get("PROGRAMFILES", r"C:\Program Files")):
        for name in ("Inno Setup 6", "Inno Setup 5"):
            p = Path(base) / name / "ISCC.exe"
            if p.exists():
                return p
    return None


def build_installer(with_training: bool) -> int:
    iscc = find_iscc()
    if iscc is None:
        say("Inno Setup not found — skipping the installer.")
        say("  install it with:  winget install -e --id JRSoftware.InnoSetup")
        say(f"  the app itself is ready to copy from: {DIST / 'PG-Label'}")
        return 1
    say(f"compiling the installer with {iscc}")
    return run([iscc, f"/DMyAppVersion={paths.APP_VERSION}",
                f"/DWithTraining={'1' if with_training else '0'}",
                str(PKG / "installer.iss")])


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--installer", action="store_true", help="also compile the Inno Setup installer")
    ap.add_argument("--no-training", action="store_true",
                    help="label-only build: omit tools/ and pseudoguard/ (no Train button)")
    ap.add_argument("--no-demo", action="store_true", help="omit the bundled sample images")
    ap.add_argument("--windowed", action="store_true", help="build without a console window")
    ap.add_argument("--clean", action="store_true", help="delete previous build artefacts first")
    ap.add_argument("--recreate-venv", action="store_true", help="rebuild the build environment")
    args = ap.parse_args(argv)

    t0 = time.time()
    say(f"{paths.APP_NAME} {paths.APP_VERSION} — building on {sys.platform} "
        f"with Python {sys.version.split()[0]}")
    if sys.platform != "win32":
        say("NOTE: not running on Windows. PyInstaller only produces an executable for the OS it "
            "runs on, so this will not yield a .exe — run this on Windows, or build the portable "
            "release with packaging/make_portable_zip.py, which works from any OS.")

    if args.clean:
        for d in (DIST, BUILD / "work"):
            if d.exists():
                say(f"removing {d}")
                if not fsutil.remove_tree(d):
                    say(f"  ! {d} is partly in use — close any program holding it and retry")

    py = ensure_build_venv(recreate=args.recreate_venv)
    ensure_icon(py)
    write_version_info()

    with_training = not args.no_training
    if with_training and not (ROOT / "pseudoguard" / "__init__.py").exists():
        say("WARNING: pseudoguard/ is missing — building label-only (the Train button is hidden).")
        with_training = False

    env = dict(os.environ)
    env["PGLABEL_WITH_DEMO"] = "0" if args.no_demo else "1"
    env["PGLABEL_WITH_TRAINING"] = "1" if with_training else "0"
    env["PGLABEL_CONSOLE"] = "0" if args.windowed else "1"

    # No --specpath here: PyInstaller rejects makespec options when it is given a .spec file.
    rc = run([py, "-m", "PyInstaller", "--noconfirm", "--clean",
              "--distpath", str(DIST), "--workpath", str(BUILD / "work"),
              str(PKG / "PG-Label.spec")], env=env)
    if rc != 0:
        say("PyInstaller failed — see the output above.")
        return rc

    exe = DIST / "PG-Label" / ("PG-Label.exe" if os.name == "nt" else "PG-Label")
    if not exe.exists():
        say(f"expected the app at {exe} but it is not there.")
        return 1
    size = sum(f.stat().st_size for f in (DIST / "PG-Label").rglob("*") if f.is_file())
    say(f"built {exe}  (folder is {size / 1024 / 1024:.0f} MB, "
        f"{'with' if with_training else 'without'} training support)")
    smoke_test(exe)

    say("auditing the bundle")
    run([sys.executable, str(PKG / "verify_build.py"), "--dist", str(DIST / "PG-Label")])

    if args.installer:
        build_installer(with_training)

    say(f"finished in {time.time() - t0:.0f}s")
    say(f"app folder : {DIST / 'PG-Label'}")
    setup = DIST / f"PG-Label-Setup-{paths.APP_VERSION}.exe"
    if setup.exists():
        say(f"installer  : {setup}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
